require "albacore"
require "./lib/underscore.rb"

specs = FileList["**/*.nuspec"]

desc "Compile the package output"
task :default => [:package]

ahk_compile :compile do |cmd| 
  cmd.in = "underscore-script/tools/underscore.ahk"
  cmd.icon = "underscore-script/tools/underscore_on.ico"
  cmd.out = "underscore-compiled/tools/underscore.exe"
end

output :output do |out|
  out.keep_to
  out.from "underscore-script/tools"
  out.to "underscore-compiled/tools"
  out.file "underscore_off.ico"
  out.file "underscore_on.ico"
end

desc "Build all of the packages"
task :package => specs

specs.each do |spec|
  exec spec => [:compile, :output] do |cmd|
    cmd.command = "cpack"
    cmd.parameters = [spec]
  end
end
